title: Mitchell Wadas
email: macaws.lockout.1x@icloud.com
github: https://github.com/mitchellwadas
description: Master's student in Mathematics at Northeastern University. My interests include commutative algebra and algebraic geometry.
footer: Last updated March 2025.
theme: minima
